import pytest

from mosaicist.ptx import Label, PTXParseError, build_cfg, parse

MINI = """
//
// Generated by a test
//
.version 8.5
.target sm_90a
.address_size 64
.file 1 "kernel.py"

.shared .align 8 .b8 bars[64];
.global .align 4 .b8 table[4] = {1, 2, 3, 4};

.func (.param .b32 retval) helper(.param .b32 x)
{
	ret;
}

.visible .entry small(
	.param .u64 small_param_0
)
.maxntid 128, 1, 1
.maxnreg 168
{
	.reg .b32 %r<8>;   /* block comment ; with a semicolon { and brace */
	.loc 1 10 3
	mov.u32 %r1, %tid.x;
$L__BB0_1: $L__BB0_alias:
	.loc 1 11 0
	{
	.reg .pred p;
	setp.ne.b32 p, %r1, 0;
	wgmma.mma_async.sync.aligned.m64n128k16.f32.bf16.bf16 {%f1, %f2}, %rd1, %rd2, p, 1, 1, 0, 1;
	}
	@!%p1 bra $L__BB0_1;
	ret;
}

.section .debug_info
{
.b8 0
}
"""


def test_module_header_and_decls():
    mod = parse(MINI)
    assert (mod.version, mod.target, mod.address_size) == ("8.5", "sm_90a", 64)
    assert mod.files == {1: "kernel.py"}
    assert [s.name for s in mod.shared] == ["bars"] and mod.shared[0].nbytes == 64
    assert [f.name for f in mod.functions] == ["helper", "small"]
    assert [e.name for e in mod.entries] == ["small"]


def test_entry_directives_params_and_body():
    fn = parse(MINI).entry()
    assert fn.params == [".param .u64 small_param_0"]
    assert fn.directives["maxntid"] == (128, 1, 1)
    assert fn.directives["maxnreg"] == (168,)
    labels = [s.name for s in fn.body if isinstance(s, Label)]
    assert labels == ["$L__BB0_1", "$L__BB0_alias"]
    ops = [i.opcode for i in fn.instrs]
    assert ops == ["mov.u32", "setp.ne.b32", "wgmma.mma_async.sync.aligned.m64n128k16.f32.bf16.bf16",
                   "bra", "ret"]


def test_vector_operands_scopes_guards_and_locs():
    fn = parse(MINI).entry()
    wg = fn.instrs[2]
    assert wg.operands[0] == "{%f1, %f2}"  # vector brace stays in the operand
    assert wg.operands[1:3] == ["%rd1", "%rd2"]
    assert str(wg.loc) == "kernel.py:11"
    assert fn.instrs[0].loc.line == 10 and fn.instrs[0].loc.col == 3
    bra = fn.instrs[3]
    assert bra.pred == "!%p1" and bra.operands == ["$L__BB0_1"]
    # line numbers refer to the original text
    assert MINI.splitlines()[wg.line - 1].strip().startswith("wgmma.mma_async")


def test_labels_are_not_duplicated_by_vector_braces():
    text = """.version 8.5
.target sm_90a
.address_size 64
.visible .entry k()
{
$L0:
	st.shared.v4.b32 [%r1], {%r2, %r3, %r4, %r5};
	ret;
}
"""
    fn = parse(text).entry()
    assert [s.name for s in fn.body if isinstance(s, Label)] == ["$L0"]


def test_entry_selection():
    two = MINI + """
.visible .entry bigger()
{
	mov.u32 %r1, 1;
	mov.u32 %r2, 2;
	mov.u32 %r3, 3;
	mov.u32 %r4, 4;
	mov.u32 %r5, 5;
	mov.u32 %r6, 6;
	mov.u32 %r7, 7;
	ret;
}
"""
    mod = parse(two)
    assert mod.entry().name == "bigger"  # largest by default
    assert mod.entry("small").name == "small"
    with pytest.raises(KeyError):
        mod.entry("nope")


def test_unterminated_statement_raises():
    with pytest.raises(PTXParseError):
        parse(".version 8.5\n.target sm_90a\n.visible .entry k()\n{\n mov.u32 %r1, 1\n}\n")


def test_fixtures_parse(ref_ptx, cand_ptx):
    for text in (ref_ptx, cand_ptx):
        fn = parse(text).entry()
        assert len(fn.instrs) > 30
        build_cfg(fn)
