"""Naive translation: contract -> a first Pallas kernel (DESIGN §5).

v0 has one job: be obviously correct. It keeps the reference's output tile shape, its
tile-to-block mapping and its K traversal order, and ignores performance -- one compute
warpgroup, a plain barrier ring, a full MMA wait every step. Keeping the tile grid means
the coarse fingerprint layers already line up at v0, so the first diff is about pipelining
and concurrency rather than about shape.

`TemplateTranslator` covers the GEMM family deterministically, which is M2's stated
scope. `Translator` is the seam an LLM backend plugs into for kernels the templates do
not cover; it returns source, and the repair loop feeds it structured failures.

The emitted module exposes `build()`, so `mosaicist capture` can run it with no glue.
"""

from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

from .contract import Contract, block_k_for, stages_for

_HEADER = '''"""Generated by mosaicist v0 translation -- naive by design, not tuned.

Contract: {name} on {arch}
  dims  {dims}
  tile  {tile}
  mma   {mma} ({mma_kind})
Deferred from the reference, to be reintroduced by the convergence loop if the diff
asks for it: {deferred}
"""

import functools

import jax
import jax.numpy as jnp
from jax import lax
from jax.experimental import pallas as pl
from jax.experimental.pallas import mosaic_gpu as plgpu

TILE_M = {tile_m}
TILE_N = {tile_n}
BLOCK_K = {block_k}
STAGES = {stages}
'''

_WGMMA_BODY = '''

def kernel(a, b):
    """(m, k) x (k, n) -> (m, n). One warpgroup, one accumulator, full wait each step."""
    m, k = a.shape
    _, n = b.shape
    num_kb = k // BLOCK_K
    swizzle = plgpu.find_swizzle(BLOCK_K * {elem_bits})
    transforms = (plgpu.TilingTransform((8, swizzle * 8 // {elem_bits})),
                  plgpu.SwizzleTransform(swizzle))

    def body(a_gmem, b_gmem, o_gmem):
        mi, ni = lax.axis_index("mi"), lax.axis_index("ni")
        m_slice, n_slice = pl.ds(mi * TILE_M, TILE_M), pl.ds(ni * TILE_N, TILE_N)

        @functools.partial(
            pl.run_scoped,
            a_smem=plgpu.SMEM((STAGES, TILE_M, BLOCK_K), a.dtype, transforms=transforms),
            b_smem=plgpu.SMEM((STAGES, BLOCK_K, TILE_N), b.dtype, transforms=transforms),
            o_smem=plgpu.SMEM((TILE_M, TILE_N), o_dtype),
            barrier=plgpu.Barrier(num_arrivals=2, num_barriers=STAGES),
            acc=plgpu.ACC((TILE_M, TILE_N), jnp.float32),
        )
        def compute(a_smem, b_smem, o_smem, barrier, acc):
            def fetch(kb, slot):
                ks = pl.ds(kb * BLOCK_K, BLOCK_K)
                plgpu.copy_gmem_to_smem(a_gmem.at[m_slice, ks], a_smem.at[slot],
                                        barrier.at[slot])
                plgpu.copy_gmem_to_smem(b_gmem.at[ks, n_slice], b_smem.at[slot],
                                        barrier.at[slot])

            for slot in range(STAGES):
                if slot < num_kb:
                    fetch(slot, slot)

            def step(kb, _):
                slot = lax.rem(kb, STAGES)
                plgpu.barrier_wait(barrier.at[slot])
                plgpu.wgmma(acc, a_smem.at[slot], b_smem.at[slot])
                plgpu.wgmma_wait(0)          # naive: drain every step

                @pl.when(kb + STAGES < num_kb)
                def _():
                    fetch(kb + STAGES, slot)
                return 0

            lax.fori_loop(0, num_kb, step, 0)
            o_smem[...] = acc[...].astype(o_dtype)
            plgpu.commit_smem()
            plgpu.copy_smem_to_gmem(o_smem, o_gmem.at[m_slice, n_slice])
            plgpu.wait_smem_to_gmem(0)

    o_dtype = jnp.{out_dtype}
    return plgpu.kernel(
        body,
        out_shape=jax.ShapeDtypeStruct((m, n), o_dtype),
        grid=(m // TILE_M, n // TILE_N),
        grid_names=("mi", "ni"),
    )(a, b)
'''

_TCGEN05_BODY = '''

def kernel(a, b):
    """(m, k) x (k, n) -> (m, n) on Blackwell. One MMA, accumulator drained once."""
    m, k = a.shape
    _, n = b.shape
    num_kb = k // BLOCK_K
    swizzle = plgpu.find_swizzle(BLOCK_K * {elem_bits})
    transforms = (plgpu.TilingTransform((8, swizzle * 8 // {elem_bits})),
                  plgpu.SwizzleTransform(swizzle))

    def body(a_gmem, b_gmem, o_gmem, a_smem, b_smem, o_smem, acc_tmem, barrier, mma_done):
        mi, ni = lax.axis_index("mi"), lax.axis_index("ni")
        m_slice, n_slice = pl.ds(mi * TILE_M, TILE_M), pl.ds(ni * TILE_N, TILE_N)

        def fetch(kb, slot):
            ks = pl.ds(kb * BLOCK_K, BLOCK_K)
            plgpu.copy_gmem_to_smem(a_gmem.at[m_slice, ks], a_smem.at[slot], barrier.at[slot])
            plgpu.copy_gmem_to_smem(b_gmem.at[ks, n_slice], b_smem.at[slot], barrier.at[slot])

        for slot in range(STAGES):
            if slot < num_kb:
                fetch(slot, slot)

        def step(kb, _):
            slot = lax.rem(kb, STAGES)
            plgpu.barrier_wait(barrier.at[slot])
            plgpu.tcgen05_mma(acc_tmem, a_smem.at[slot], b_smem.at[slot],
                              accumulate=kb > 0)

            @pl.when(kb + STAGES < num_kb)
            def _():
                fetch(kb + STAGES, slot)
            return 0

        lax.fori_loop(0, num_kb, step, 0)
        plgpu.tcgen05_commit_arrive(mma_done)
        plgpu.barrier_wait(mma_done)
        vals = plgpu.async_load_tmem(acc_tmem)
        plgpu.wait_load_tmem()
        o_smem[...] = vals.astype(o_dtype)
        plgpu.commit_smem()
        plgpu.copy_smem_to_gmem(o_smem, o_gmem.at[m_slice, n_slice])
        plgpu.wait_smem_to_gmem(0)

    o_dtype = jnp.{out_dtype}
    return plgpu.kernel(
        body,
        out_shape=jax.ShapeDtypeStruct((m, n), o_dtype),
        grid=(m // TILE_M, n // TILE_N),
        grid_names=("mi", "ni"),
        scratch_shapes=[
            plgpu.SMEM((STAGES, TILE_M, BLOCK_K), a.dtype, transforms=transforms),
            plgpu.SMEM((STAGES, BLOCK_K, TILE_N), b.dtype, transforms=transforms),
            plgpu.SMEM((TILE_M, TILE_N), o_dtype),
            plgpu.TMEM((TILE_M, TILE_N), jnp.float32),
            plgpu.Barrier(num_arrivals=2, num_barriers=STAGES),
            plgpu.Barrier(orders_tensor_core=True),
        ],
    )(a, b)
'''

_BUILD = '''

def build():
    """Entry point for `mosaicist capture`: returns (callable, args)."""
    import jax

    m, n, k = {m}, {n}, {k}
    key = jax.random.split(jax.random.key(0), 2)
    a = jax.random.normal(key[0], (m, k), jnp.float32).astype(jnp.{in_dtype})
    b = jax.random.normal(key[1], (k, n), jnp.float32).astype(jnp.{in_dtype})
    return jax.jit(kernel), (a, b)


def reference(a, b):
    """float64 oracle for the numerics gate."""
    import numpy as np

    return np.asarray(a, np.float64) @ np.asarray(b, np.float64)
'''


class Translator(Protocol):
    """A source-emitting backend. `TemplateTranslator` is the deterministic one; an LLM
    backend implements the same call and gets `hints` from the repair loop."""

    def emit(self, contract: Contract, hints: list[str] | None = None) -> str: ...


@dataclass
class TemplateTranslator:
    """Deterministic v0 for the GEMM family."""

    def emit(self, contract: Contract, hints: list[str] | None = None) -> str:
        tile_m = contract.tile.get("m", 128)
        tile_n = contract.tile.get("n", 128)
        block_k = block_k_for(contract)
        stages = stages_for(contract, block_k)
        in_dtype = contract.operands[0].dtype if contract.operands else "bfloat16"
        elem_bits = {"float4_e2m1fn": 4, "float8_e4m3fn": 8,
                     "bfloat16": 16, "float16": 16, "float32": 32}.get(in_dtype, 16)

        for h in hints or []:
            if "accumulator" in h:
                pass  # the templates already accumulate in f32; nothing to widen
            if "boundary" in h:
                tile_m = min(tile_m, contract.dims.get("m", tile_m))
            if "stages" in h:
                stages = 1

        head = _HEADER.format(
            name=contract.name, arch=contract.arch, dims=contract.dims, tile=contract.tile,
            mma=contract.mma, mma_kind=contract.mma_kind,
            deferred=", ".join(contract.deferred) or "nothing",
            tile_m=tile_m, tile_n=tile_n, block_k=block_k, stages=stages)
        body = (_TCGEN05_BODY if contract.mma == "tcgen05" else _WGMMA_BODY).format(
            out_dtype=contract.out_dtype, elem_bits=elem_bits)
        tail = _BUILD.format(m=contract.dims.get("m", tile_m), n=contract.dims.get("n", tile_n),
                             k=contract.dims.get("k", block_k), in_dtype=in_dtype)
        return head + body + tail


def emit_v0(contract: Contract, path: str | Path,
            translator: Translator | None = None, hints: list[str] | None = None) -> Path:
    """Write v0 for `contract` to `path` and return it."""
    src = (translator or TemplateTranslator()).emit(contract, hints)
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(src)
    return p


@dataclass
class TranslationResult:
    path: Path
    rounds: int
    report: object | None = None
    hints: list[str] = field(default_factory=list)

    @property
    def passed(self) -> bool:
        return self.report is None or getattr(self.report, "passed", False)


def translate_until_correct(contract: Contract, path: str | Path, capture_fn,
                            gate_fn, translator: Translator | None = None,
                            max_rounds: int = 3) -> TranslationResult:
    """Emit v0, run it, gate it, and re-emit with hints until it passes (DESIGN §5).

    `capture_fn(module_path) -> Bundle` runs the emitted module; `gate_fn(bundle) ->
    NumericsReport` judges it. Both are injected because running a kernel needs a GPU
    and a framework, and this module should stay importable without either.

    The hints are the structured error map the design describes: the translator is told
    what shape the failure had, not merely that there was one.
    """
    tr = translator or TemplateTranslator()
    hints: list[str] = []
    report = None
    for r in range(1, max_rounds + 1):
        p = emit_v0(contract, path, tr, hints)
        bundle = capture_fn(p)
        report = gate_fn(bundle)
        if getattr(report, "passed", False):
            return TranslationResult(path=p, rounds=r, report=report, hints=hints)
        new_hints = repair_hints(report)
        if not new_hints or new_hints == hints:
            # the same diagnosis twice means another round would emit the same source
            return TranslationResult(path=p, rounds=r, report=report, hints=new_hints)
        hints = new_hints
    return TranslationResult(path=Path(path), rounds=max_rounds, report=report, hints=hints)


def repair_hints(report) -> list[str]:
    """Turn a numerics failure into hints the translator can act on (DESIGN §5, step 2).

    The mapping is the one the design calls out: a failure confined to the last tile row
    is boundary masking, and error that grows with K is the accumulator.
    """
    hints: list[str] = []
    if getattr(report, "passed", True):
        return hints
    frac = getattr(report, "worse_fraction", None)
    if frac is None:  # fall back to how much of the output is not bit-identical
        frac = 1.0 - (getattr(report, "bitwise_equal_fraction", 0.0) or 0.0)
    if 0 < frac < 0.15:
        hints.append("failure is confined to a few tiles: check boundary masking")
    else:
        hints.append("failure is spread over the output: check the accumulator dtype "
                     "and the K traversal order")
    if getattr(report, "special_mismatch", 0):
        hints.append("NaN/Inf placement differs: check masked-lane initialisation")
    return hints
