"""Generated by mosaicist v0 translation -- naive by design, not tuned.

Contract: gemm_sm_100a on sm_100a
  dims  {'m': 512, 'n': 512, 'k': 1024}
  tile  {'m': 128, 'n': 128}
  mma   tcgen05 (f16)
Deferred from the reference, to be reintroduced by the convergence loop if the diff
asks for it: nothing
"""

import functools

import jax
import jax.numpy as jnp
from jax import lax
from jax.experimental import pallas as pl
from jax.experimental.pallas import mosaic_gpu as plgpu

TILE_M = 128
TILE_N = 128
BLOCK_K = 64
STAGES = 2


def kernel(a, b):
    """(m, k) x (k, n) -> (m, n) on Blackwell. One MMA, accumulator drained once."""
    m, k = a.shape
    _, n = b.shape
    num_kb = k // BLOCK_K
    swizzle = plgpu.find_swizzle(BLOCK_K * 16)
    transforms = (plgpu.TilingTransform((8, swizzle * 8 // 16)),
                  plgpu.SwizzleTransform(swizzle))

    def body(a_gmem, b_gmem, o_gmem, a_smem, b_smem, o_smem, acc_tmem, barrier, mma_done):
        mi, ni = lax.axis_index("mi"), lax.axis_index("ni")
        m_slice, n_slice = pl.ds(mi * TILE_M, TILE_M), pl.ds(ni * TILE_N, TILE_N)

        def fetch(kb, slot):
            ks = pl.ds(kb * BLOCK_K, BLOCK_K)
            plgpu.copy_gmem_to_smem(a_gmem.at[m_slice, ks], a_smem.at[slot], barrier.at[slot])
            plgpu.copy_gmem_to_smem(b_gmem.at[ks, n_slice], b_smem.at[slot], barrier.at[slot])

        for slot in range(STAGES):
            if slot < num_kb:
                fetch(slot, slot)

        def step(kb, _):
            slot = lax.rem(kb, STAGES)
            plgpu.barrier_wait(barrier.at[slot])
            plgpu.tcgen05_mma(acc_tmem, a_smem.at[slot], b_smem.at[slot],
                              accumulate=kb > 0)

            @pl.when(kb + STAGES < num_kb)
            def _():
                fetch(kb + STAGES, slot)
            return 0

        lax.fori_loop(0, num_kb, step, 0)
        plgpu.tcgen05_commit_arrive(mma_done)
        plgpu.barrier_wait(mma_done)
        vals = plgpu.async_load_tmem(acc_tmem)
        plgpu.wait_load_tmem()
        o_smem[...] = vals.astype(o_dtype)
        plgpu.commit_smem()
        plgpu.copy_smem_to_gmem(o_smem, o_gmem.at[m_slice, n_slice])
        plgpu.wait_smem_to_gmem(0)

    o_dtype = jnp.bfloat16
    return plgpu.kernel(
        body,
        out_shape=jax.ShapeDtypeStruct((m, n), o_dtype),
        grid=(m // TILE_M, n // TILE_N),
        grid_names=("mi", "ni"),
        scratch_shapes=[
            plgpu.SMEM((STAGES, TILE_M, BLOCK_K), a.dtype, transforms=transforms),
            plgpu.SMEM((STAGES, BLOCK_K, TILE_N), b.dtype, transforms=transforms),
            plgpu.SMEM((TILE_M, TILE_N), o_dtype),
            plgpu.TMEM((TILE_M, TILE_N), jnp.float32),
            plgpu.Barrier(num_arrivals=2, num_barriers=STAGES),
            plgpu.Barrier(orders_tensor_core=True),
        ],
    )(a, b)


def build():
    """Entry point for `mosaicist capture`: returns (callable, args)."""
    import jax

    m, n, k = 512, 512, 1024
    key = jax.random.split(jax.random.key(0), 2)
    a = jax.random.normal(key[0], (m, k), jnp.float32).astype(jnp.bfloat16)
    b = jax.random.normal(key[1], (k, n), jnp.float32).astype(jnp.bfloat16)
    return jax.jit(kernel), (a, b)


def reference(a, b):
    """float64 oracle for the numerics gate."""
    import numpy as np

    return np.asarray(a, np.float64) @ np.asarray(b, np.float64)
